use crate::util::errors::ContainerResult;

/// Write /etc/resolv.conf to the container rootfs.
pub fn write_resolv_conf(
    rootfs: &std::path::Path,
    dns_servers: &[std::net::IpAddr],
) -> ContainerResult<()> {
    let resolv_path = rootfs.join("etc").join("resolv.conf");
    if !resolv_path.exists() {
        return Ok(());
    }

    let mut content = String::from("# Generated by container-engine\n");
    for dns in dns_servers {
        content.push_str(&format!("nameserver {dns}\n"));
    }
    content.push_str("options ndots:0\n");

    std::fs::write(&resolv_path, content.as_bytes())?;
    Ok(())
}
