[workspace]
members = [
    "common-protocol",
    "columnar-engine",
    "core-sys",
    "crdt-engine",
    "lob-engine",
    "telemetry-aggregator",
    "sensor-fusion-buffer",
    "lsm-engine",
    "sql-engine",
    "admin-tools",
    "platform-nodes",
    "src-tauri",
    "container-engine",
    "log-broker",
    "raft-kv",
    "compute-orchestrator",
    "api-gateway",
    "render-engine",
    "ingestion-server",
    "sync-server",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = false
split-debuginfo = "off"
